[package]
name = "run-vm"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
json = "0.12"
libc = "0.2"
log = "0.4"
nix = "0.22"
simplelog = "0.10"
tokio = { version = "1.10", features = ["full"] }
